FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY demoairbnb/ ./demoairbnb/
COPY init_db.sh /app/init_db.sh

# Normalize line endings (works around Windows CRLF) and make executable
RUN sed -i 's/\r$//' /app/init_db.sh && chmod +x /app/init_db.sh


ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=demoairbnb.settings

EXPOSE 8000

CMD ["/app/init_db.sh"]
