# Generated by Django 5.2.12 on 2026-05-14 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0003_reservation_agent_commission_reservation_amount_paid_and_more'),
        ('core', '0002_invitation_codes_and_cleanup'),
        ('inventory', '0002_property_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center', to='inventory.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('INCOME', 'Ingreso por alquiler'), ('CLEANING_COST', 'Costo de limpieza'), ('MAINTENANCE', 'Mantenimiento / reparación'), ('UTILITIES', 'Servicios públicos'), ('COMMISSION', 'Comisión a intermediarios'), ('OTHER_EXPENSE', 'Otro gasto'), ('OTHER_INCOME', 'Otro ingreso')], default='INCOME', max_length=20)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('reference_type', models.CharField(blank=True, max_length=40)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.analyticaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('type', models.CharField(choices=[('ADVANCE', 'Anticipo'), ('BALANCE', 'Pago de saldo'), ('REFUND', 'Reembolso')], default='ADVANCE', max_length=10)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia bancaria'), ('OTHER', 'Otro (especificar en notas)')], default='CASH', max_length=10)),
                ('reference', models.CharField(blank=True, help_text='Optional external reference: bank confirmation #, voucher number, deposit slip ID, etc.', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='booking.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('value', models.DecimalField(decimal_places=4, help_text='If type=PERCENT, this is a fraction (0.19 = 19%). If type=FIXED, this is a flat amount in the tenant currency.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('type', models.CharField(choices=[('PERCENT', 'Porcentaje'), ('FIXED', 'Valor fijo')], default='PERCENT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticaccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='tenant_unique_analytic_account_name'),
        ),
        migrations.AddIndex(
            model_name='analyticline',
            index=models.Index(fields=['account', '-date'], name='finance_ana_account_66a0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticline',
            index=models.Index(fields=['tenant', 'category', '-date'], name='finance_ana_tenant__e789b2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reservation', '-date'], name='finance_pay_reserva_5421c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='tenant_unique_tax_name'),
        ),
    ]
