# Generated by Django 5.2.12 on 2026-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_historicalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='type',
            field=models.CharField(choices=[('ADVANCE', 'Anticipo (alojamiento)'), ('BALANCE', 'Pago de saldo (alojamiento)'), ('EXTRA', 'Pago extra (daños / servicios adicionales)'), ('REFUND', 'Reembolso')], default='ADVANCE', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('ADVANCE', 'Anticipo (alojamiento)'), ('BALANCE', 'Pago de saldo (alojamiento)'), ('EXTRA', 'Pago extra (daños / servicios adicionales)'), ('REFUND', 'Reembolso')], default='ADVANCE', max_length=10),
        ),
    ]
