# Generated by Django 5.2.12 on 2026-05-20 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailtemplate'),
        ('finance', '0003_alter_historicalpayment_type_alter_payment_type'),
        ('inventory', '0002_property_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('voucher_type', models.CharField(choices=[('stay', 'Comprobante de Estadía'), ('payment', 'Recibo de Pago'), ('invoice', 'Factura')], max_length=20)),
                ('status', models.CharField(choices=[('issued', 'Emitido'), ('sent', 'Enviado'), ('downloaded', 'Descargado'), ('voided', 'Anulado')], default='issued', max_length=20)),
                ('guest_name', models.CharField(max_length=160)),
                ('guest_email', models.EmailField(max_length=254)),
                ('property_name', models.CharField(max_length=160)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='vouchers/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyProfitabilityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commissions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cleaning_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('maintenance_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('utilities_costs', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fees', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('property_management_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('profit_margin', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('occupied_nights', models.IntegerField(default=0)),
                ('total_nights', models.IntegerField(default=0)),
                ('occupancy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('avg_daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_per_available_night', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_reports', to='inventory.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('property', 'year', 'month'), name='unique_property_profitability_period')],
            },
        ),
    ]
