# Generated by Django 5.2.12 on 2026-03-11 12:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('type', models.CharField(choices=[('GUEST', 'Guest'), ('AGENT', 'Agent'), ('PLATFORM', 'Platform')], default='GUEST', max_length=16)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Only applies for AGENT type contacts.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('NEW', 'New'), ('QUOTED', 'Quoted'), ('WON', 'Won'), ('LOST', 'Lost')], default='NEW', max_length=16)),
                ('desired_check_in', models.DateField(blank=True, null=True)),
                ('desired_check_out', models.DateField(blank=True, null=True)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='crm.contact')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('tenant', 'email'), name='tenant_unique_contact_email'),
        ),
    ]
