# Generated by Django 5.2.12 on 2026-05-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalinvitationcode_historicaltenant_and_more'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='tax_id',
            field=models.CharField(blank=True, help_text='Cédula / RUT / NIT / VAT — identificación fiscal.', max_length=40),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id', ''), _negated=True), fields=('tenant', 'tax_id'), name='tenant_unique_contact_tax_id'),
        ),
    ]
