# Generated by Django 5.2.12 on 2026-05-14 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0005_historicalreservation'),
        ('core', '0003_historicalinvitationcode_historicaltenant_and_more'),
        ('inventory', '0002_property_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('INTERNAL', 'Interno')], default='WHATSAPP', max_length=12)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='tenant_unique_template_name')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CLEANING', 'Limpieza'), ('MAINTENANCE', 'Mantenimiento'), ('INSPECTION', 'Inspección'), ('OTHER', 'Otra')], default='CLEANING', max_length=12)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En curso'), ('DONE', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='inventory.property')),
                ('reservation', models.ForeignKey(blank=True, help_text='Optional link to the reservation that triggered the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='booking.reservation')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['due_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'due_date'], name='ops_task_tenant__0d869c_idx'), models.Index(fields=['tenant', 'assigned_to', 'status'], name='ops_task_tenant__3ecac0_idx')],
            },
        ),
    ]
