# Generated by Django 5.2.12 on 2026-05-14 02:28

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        ('core', '0002_invitation_codes_and_cleanup'),
        ('inventory', '0002_property_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='agent_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Sin pagos'), ('PARTIAL', 'Pagado parcialmente'), ('PAID', 'Pagado completo'), ('OVERPAID', 'Sobrepagado')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked-in'), ('CHECKED_OUT', 'Checked-out'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=16),
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_percent', models.BooleanField(default=False, help_text='If True, modifier multiplies the base price (1.20 = +20%). If False, modifier replaces it as a flat nightly rate.')),
                ('modifier', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_nights', models.PositiveIntegerField(default=1, help_text='Minimum nights required when this rule applies.')),
                ('priority', models.PositiveIntegerField(default=10, help_text='Higher value wins when multiple rules overlap.')),
                ('is_active', models.BooleanField(default=True)),
                ('properties', models.ManyToManyField(blank=True, help_text='Empty = applies to ALL tenant properties.', related_name='price_rules', to='inventory.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-priority', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ReservationLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('NIGHT', 'Cargo por noche'), ('FEE', 'Tarifa única (limpieza, etc.)'), ('EXTRA', 'Servicio adicional'), ('DISCOUNT', 'Descuento')], default='NIGHT', max_length=10)),
                ('description', models.CharField(max_length=240)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='booking.reservation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
