# Generated by Django 5.2.4 on 2026-05-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('ical', 'iCal (externo)')], default='manual', max_length=20),
        ),
    ]
