# Generated by Django 5.2.12 on 2026-05-14 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_reservation_agent_commission_reservation_amount_paid_and_more'),
        ('core', '0002_invitation_codes_and_cleanup'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationline',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='lines', to='finance.tax'),
        ),
        migrations.AddField(
            model_name='reservationline',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='pricerule',
            index=models.Index(fields=['tenant', 'is_active', 'start_date', 'end_date'], name='booking_pri_tenant__b64e78_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricerule',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='pricerule_end_after_start'),
        ),
    ]
