# Generated by Django 5.2.12 on 2026-05-15 11:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_historicalreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalreservation',
            name='extras_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of EXTRA-type payments (damages, extra services). Does NOT count toward the lodging balance_due.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extras_received',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sum of EXTRA-type payments (damages, extra services). Does NOT count toward the lodging balance_due.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
