# Generated by Django 5.2.12 on 2026-05-14 01:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('purpose', models.CharField(choices=[('CREATE_TENANT', 'Crear nueva empresa (tenant)'), ('JOIN_TENANT', 'Unirse a empresa existente')], default='CREATE_TENANT', max_length=20)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_codes_created', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, help_text='Optional role to assign when JOIN_TENANT code is used.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_codes', to='core.tenantrole')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation_codes', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'is_active'], name='core_invita_purpose_d08326_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_uses__gte', 1)), name='invitationcode_max_uses_positive')],
            },
        ),
    ]
