# Generated by Django 5.2.4 on 2026-05-20 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refresh_token_encrypted', models.TextField()),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('google_account_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=False)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=16)),
                ('last_sync_error', models.TextField(blank=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_credential', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
