# Generated by Django 5.2.12 on 2026-05-20 11:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalinvitationcode_historicaltenant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Nombre interno de la plantilla', max_length=120)),
                ('template_type', models.CharField(choices=[('booking_confirmation', 'Confirmación de Reserva'), ('booking_reminder', 'Recordatorio de Reserva'), ('booking_cancellation', 'Cancelación de Reserva'), ('guest_welcome', 'Bienvenida Huésped'), ('guest_review_request', 'Solicitud de Reseña'), ('owner_daily_summary', 'Resumen Diario Propietario'), ('payment_receipt', 'Recibo de Pago'), ('custom', 'Personalizado')], help_text='Tipo de plantilla para categorización', max_length=30)),
                ('subject', models.CharField(blank=True, help_text='Asunto del email. Soporta variables: {guest_name}, {property_name}, etc.', max_length=255)),
                ('body', models.TextField(help_text='Cuerpo del mensaje. Soporta variables: {guest_name}, {property_name}, {check_in}, {check_out}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Plantilla por defecto para su tipo')),
                ('variables_used', models.JSONField(blank=True, default=list, help_text="Lista de variables usadas: ['guest_name', 'property_name']")),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['template_type', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'template_type'), name='tenant_single_default_email_template'), models.UniqueConstraint(fields=('tenant', 'name'), name='tenant_email_template_unique_name')],
            },
        ),
    ]
