# Generated by Django 5.2.14 on 2026-05-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emailtemplate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='googlecalendarcredential',
            name='unique_google_cred_per_tenant',
        ),
        migrations.AddField(
            model_name='googlecalendarcredential',
            name='google_account_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='calendar_id',
            field=models.CharField(default='primary', max_length=255),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='last_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('connected', 'Connected'), ('error', 'Error')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='refresh_token_encrypted',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='googlecalendarcredential',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_credential', to='core.tenant'),
        ),
    ]
