# Generated by Django 5.2.4 on 2026-05-20 11:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_googlecalendarcredential'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyICalFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="Etiqueta legible: 'Airbnb', 'Booking.com', etc.", max_length=80)),
                ('ical_url', models.URLField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(choices=[('never', 'Never'), ('ok', 'OK'), ('error', 'Error')], default='never', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ical_feeds', to='inventory.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['property__name', 'label'],
                'constraints': [models.UniqueConstraint(fields=('property', 'ical_url'), name='ical_feed_unique_property_url')],
            },
        ),
    ]
