# Generated by Django 5.2.4 on 2026-05-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyicalfeed',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddConstraint(
            model_name='propertyicalfeed',
            constraint=models.UniqueConstraint(fields=('property', 'ical_url'), name='ical_feed_unique_property_url'),
        ),
    ]
